Bug fix for PESSTOEFOSC2dSPEC on some systems
When I run pipeline on my linux workstation with anaconda python 2.7, I get the error:
AttributeError: Package onedspec has not been loaded; no tasks are defined.

Adding this line fixes the bug